/*
LibAndria version 4
A C-based general purpose utility library.
Copyright (c) 2025 Jared A. Maddox

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

This grant of rights is subject to two conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

And:

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "../detect.h"

#if LIBANDRIA4_PRIMITIVE_PLATDET_CALCFLOAT_H
# define LIBANDRIA4_PRIMITIVE_PLATDET_CALCFLOAT_H
	
	#undef LIBANDRIA4_FLOATTYPE_SIZE
	#undef LIBANDRIA4_LFLOATTYPE_SIZE
	#undef LIBANDRIA4_LLFLOATTYPE_SIZE
	#undef LIBANDRIA4_FLOATTYPE_TYPE
	#undef LIBANDRIA4_LFLOATTYPE_TYPE
	#undef LIBANDRIA4_LLFLOATTYPE_TYPE
	
	/* TODO: Figure out how to tell whether we should use signed or unsigned! */
	#define LIBANDRIA4_FLOATTYPE_TYPE float
	#define LIBANDRIA4_LFLOATTYPE_TYPE double
	#define LIBANDRIA4_LLFLOATTYPE_TYPE long double
	
	#if LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_MSVC )
		#if LIBANDRIA4_TARGETPROCESSOR0 != LIBANDRIA4_PROCESSOR0_ISA_x86
			#error "Unsupported processor for MSVC.\n"
		#endif
		
		#define LIBANDRIA4_FLOATTYPE_SIZE ( 4 )
		#define LIBANDRIA4_LFLOATTYPE_SIZE ( 8 )
		#define LIBANDRIA4_LLFLOATTYPE_SIZE ( 8 )
		
	#elif LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_GNU )
	#elif LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_LLVM )
	#elif LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_TCC )
	#elif \
		LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_DIGIMARS ) \
		LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_DJGPP ) \
		LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_WATCOM ) \
		LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_BORLAND ) \
		LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_PCC ) \
		LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_LCC ) \
		LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_SDCC ) \
		LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_ACK ) \
		LIBANDRIA4_COMPILER_IS_CODEBASE( LIBANDRIA4_COMPILER_CODEBASE_AZTECC )
		
		#error "Unsupported compiler, add support.\n"
		/*
			LIBANDRIA4_PLATFORMPREVIEW0 == LIBANDRIA4_PLATFORM0_NIX
			LIBANDRIA4_PLATFORMPREVIEW0 == LIBANDRIA4_PLATFORM0_MSWIN
			LIBANDRIA4_PLATFORMPREVIEW0 == LIBANDRIA4_PLATFORM0_DOS
		*/
	#else
		#error "Unrecognized compiler.\n"
	#endif
	
#endif /* End primitive platdet calcfloat.h */
